### ISSUE TITLE
Points not always being added to account.

### ISSUE THREAD

**Issue by hexabyt3** [Dan-McL/Challenge-Master#14]
Points for solving a challenge are not being added for some accounts, an example of this would be my account (hexabyt3) with two challenges solved but no points awarded.

**Comment by Dan-McL** [comment]
Did this happen today at around 1pm? Did you get the message saying you are "correct and will receive point shortly"?

**Comment by Dan-McL** [comment]
I believe this is because you entered the wager and lost 4 points.  How many challenges have you solved? If it is two you would have had 4 points prior to joining the wager then had 0 after the wager.
